server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.allyes.minimec: DEBUG

spring:
  thymeleaf:
    enabled: true
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    # 使用druid数据源
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/miniec-dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      useGlobalDataSourceStat: true
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirms: true
#    virtualHost: /

#mybatis配置
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
mybatis:
  type-aliases-package: com.allyes.minimec.domain.model.**
  mapper-locations: classpath:mapper/**/*.xml

#swagger配置
swagger:
  enable: true
  title: 用户API接口
  description: 用户API接口定义文档.
  version: 1.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  base-package: com.allyes.minimec
  base-path: /**
  exclude-path:

jwt:
  api:
    token:
      #token密钥
      app-secret: 63YUQdYDOazpqQ34aTJHolDGBpskBY
      #token签名
      app-issuer: api-test